import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import api from '../api/client';
import StepIndicator from '../components/StepIndicator';

const WIZARD_STEPS = ['Product Details', 'Record & Capture', 'Generate', 'Result'];

export default function ResultPage() {
  const { id } = useParams();
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchResult() {
      try {
        const data = await api.getResult(id);
        setResult(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    fetchResult();
  }, [id]);

  if (loading) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <p className="text-gray-500">Loading result...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16">
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
          {error}
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <StepIndicator steps={WIZARD_STEPS} current={4} />

      <div className="text-center mb-10">
        <h1 className="text-3xl font-bold mb-2">Your Demo Video is Ready</h1>
        <p className="text-gray-500">
          {result?.productName} &mdash; Generated with Amazon Nova
        </p>
      </div>

      {/* Video Preview */}
      {result?.video?.url ? (
        <div className="bg-black rounded-xl overflow-hidden mb-8 shadow-lg">
          <video
            controls
            className="w-full"
            src={result.video.url}
          >
            Your browser does not support the video tag.
          </video>
        </div>
      ) : (
        <div className="bg-gray-100 rounded-xl p-16 text-center mb-8">
          <p className="text-gray-500">
            {result?.status === 'completed'
              ? 'Video will appear here once the signed URL is refreshed.'
              : `Status: ${result?.status || 'unknown'}`}
          </p>
        </div>
      )}

      {/* Actions */}
      <div className="flex justify-center gap-4 mb-12">
        {result?.video?.url && (
          <a
            href={result.video.url}
            download
            className="px-8 py-3 bg-brand-600 text-white font-semibold rounded-lg hover:bg-brand-700 transition-colors"
          >
            Download MP4
          </a>
        )}
        <Link
          to="/"
          className="px-8 py-3 border border-gray-300 text-gray-700 font-semibold rounded-lg hover:bg-gray-50 transition-colors"
        >
          Create Another
        </Link>
      </div>

      {/* Generated Content Summary */}
      {result?.content && (
        <div className="space-y-6">
          <h2 className="text-xl font-bold">Generated Content</h2>

          {result.content.brief && (
            <ContentCard title="Product Brief">
              <p>{result.content.brief.productSummary}</p>
              {result.content.brief.keyMessages && (
                <ul className="mt-3 space-y-1">
                  {result.content.brief.keyMessages.map((m, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                      <span className="text-brand-500 mt-0.5">&#8226;</span>
                      {m}
                    </li>
                  ))}
                </ul>
              )}
            </ContentCard>
          )}

          {result.content.script && (
            <ContentCard title="Demo Script">
              <p className="text-sm text-gray-600 whitespace-pre-line leading-relaxed">
                {result.content.script.fullScript}
              </p>
            </ContentCard>
          )}

          {result.content.narration && (
            <ContentCard title="Narration">
              <p className="text-sm text-gray-600 whitespace-pre-line leading-relaxed">
                {result.content.narration.fullNarration}
              </p>
            </ContentCard>
          )}
        </div>
      )}

      {/* Nova Attribution */}
      <div className="mt-12 py-6 text-center border-t border-gray-200">
        <p className="text-xs text-gray-400">
          Content generated by Amazon Nova via Amazon Bedrock.
          Voice generated by ElevenLabs. Video assembled with FFmpeg.
        </p>
      </div>
    </div>
  );
}

function ContentCard({ title, children }) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6">
      <h3 className="font-semibold mb-3">{title}</h3>
      {children}
    </div>
  );
}
